// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhtlzcvjlwterpvufdwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFodGx6Y3ZqbHd0ZXJwdnVmZHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjgxMzYsImV4cCI6MjA2NTQwNDEzNn0.CsVH0i0GW-SAxW1-o9UOxp59Kugh8lD-QEZ-xSGahD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);